server:
  port: 8084

spring:
  application:
    name: preview-service-dev

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.pebble.preview: DEBUG
    org.springframework.security: DEBUG
